import { faBook, 
    faFolder, 
    faUserGraduate, 
    faUserEdit, 
    faBan, 
    faComment, 
    faLayerGroup, 
    faChartLine, 
    faCircle, 
    faPlus, 
    faTrashAlt, 
    faExclamation, 
    faExclamationCircle,
    faQuoteLeft,
    faUpload,
    faCheckCircle,
    faTimesCircle,
    faMapMarkerAlt,
    faEnvelope,
    faPhone} from '@fortawesome/free-solid-svg-icons';

    import { faFacebook, faTwitter, faInstagram } from '@fortawesome/free-brands-svg-icons' ;


export const iconMapping = {
    "Dashboard": "",
    "Modules": faBook,
    "Files": faFolder,
    "Exams": faUserEdit,
    "Grades": faChartLine,
    "Students": faUserGraduate,
    "Flashcards": faLayerGroup,
    "Discussions": faComment,
    "NotPublished": faBan,
    "Circle": faCircle,
    "Plus": faPlus,
    "Trash": faTrashAlt,
    "Exclamation":faExclamation,
    "Error": faExclamationCircle,
    "QuoteLeft":faQuoteLeft,
    "Upload": faUpload,
    "tick": faCheckCircle,
    "cross": faTimesCircle,
    "facebook": faFacebook,
    "twitter": faTwitter,
    "instagram": faInstagram,
    "map": faMapMarkerAlt,
    "phone": faPhone,
    "mail": faEnvelope
};