export const LOGIN_USER_STARTED = "LOGIN_USER_STARTED";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGIN_USER_SUCESS = "LOGIN_USER_SUCCESS";

export const LOGOUT_USER_STARTED = "LOGOUT_USER_STARTED";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
export const LOGOUT_USER_SUCESS = "LOGOUT_USER_SUCCESS";

export const REGISTERATION_STARTED = "REGISTRATION_STARTED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const GET_STUDENT_LIST_STARTED = "GET_STUDENT_LIST_STARTED";
export const GET_STUDENT_LIST_FAILED = "GET_STUDENT_LIST_FAILED";
export const GET_STUDENT_LIST_SUCCESS = "GET_STUDENT_LIST_SUCCESS";

export const GET_EXAM_LIST_STARTED = "GET_EXAM_LIST_STARTED";
export const GET_EXAM_LIST_FAILED = "GET_EXAM_LIST_FAILED";
export const GET_EXAM_LIST_SUCCESS = "GET_EXAM_LIST_SUCCESS";

export const SUBMIT_EXAM_STARTED = "SUBMIT_EXAM_STARTED";
export const SUBMIT_EXAM_FAILED = "SUBMIT_EXAM_FAILED";
export const SUBMIT_EXAM_SUCCESS = "SUBMIT_EXAM_SUCCESS";

export const GET_EXAM_STARTED = "GET_EXAM_STARTED";
export const GET_EXAM_FAILED = "GET_EXAM_FAILED";
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";

export const CREATE_EXAM_STARTED = "CREATE_EXAM_STARTED";
export const CREATE_EXAM_FAILED = "CREATE_EXAM_FAILED";
export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS";

export const DELETE_EXAM_STARTED = "DELETE_EXAM_STARTED";
export const DELETE_EXAM_FAILED = "DELETE_EXAM_FAILED";
export const DELETE_EXAM_SUCCESS = "DELETE_EXAM_SUCCESS";

export const GET_GRADES_LIST_STARTED = "GET_GRADES_LIST_STARTED";
export const GET_GRADES_LIST_FAILED = "GET_GRADES_LIST_FAILED";
export const GET_GRADES_LIST_SUCCESS = "GET_GRADES_LIST_SUCCESS";

export const GET_DISCUSSION_LIST_STARTED = "GET_DISCUSSION_LIST_STARTED";
export const GET_DISCUSSION_LIST_FAILED = "GET_DISCUSSION_LIST_FAILED";
export const GET_DISCUSSION_LIST_SUCCESS = "GET_DISCUSSION_LIST_SUCCESS";

export const CREATE_DISCUSSION_STARTED = "CREATE_DISCUSSION_STARTED";
export const CREATE_DICUSSION_FAILED = "CREATE_DICUSSION_FAILED";
export const CREATE_DISCUSSION_SUCCESS= "CREATE_DISCUSSION_SUCCESS";

export const REPLY_TO_DISCUSSION_STARTED = "REPLY_TO_DISCUSSION_STARTED";
export const REPLY_TO_DICUSSION_FAILED = " REPLY_TO_DICUSSION_FAILED";
export const REPLY_TO_DISCUSSION_SUCCESS = "REPLY_TO_DISCUSSION_SUCCESS";

export const EDIT_DISCUSSIO_STARTED = "EDIT_DISCUSSIO_STARTED";
export const EDIT_DICUSSION_FAILED = "EDIT_DICUSSION_FAILED";
export const EDIT_DISCUSSION_SUCCESS = "EDIT_DISCUSSION_SUCCESS";

export const GET_MODULE_LIST_STARTED = "GET_MODULE_LIST_STARTED";
export const GET_MODULE_LIST_FAILED = "GET_MODULE_LIST_FAILED";
export const GET_MODULE_LIST_SUCCESS = "GET_MODULE_LIST_SUCCESS";

export const GET_FC_SET_STARTED ="GET_FC_SET_STARTED";
export const GET_FC_SET_SUCCESS ="GET_FC_SET_SUCCESS";
export const GET_FC_SET_FAILED ="GET_FC_SET_FAILED";

export const SET_SELECTED_MODULE = "SET_SELECTED_MODULE";
export const SET_SELECTED_EXAM = "SET_SELECTED_EXAM";
export const RESET_TOAST = "RESET_TOAST";