export const LOGIN_USER_STARTED = "LOGIN_USER_STARTED";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGIN_USER_SUCESS = "LOGIN_USER_SUCCESS";

export const REGISTERATION_STARTED = "REGISTRATION_STARTED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const SET_SELECTED_MODULE = "SET_SELECTED_MODULE";