export const LOGIN_USER_STARTED = "LOGIN_USER_STARTED";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGIN_USER_SUCESS = "LOGIN_USER_SUCCESS";

export const LOGOUT_USER_STARTED = "LOGOUT_USER_STARTED";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
export const LOGOUT_USER_SUCESS = "LOGOUT_USER_SUCCESS";

export const REGISTERATION_STARTED = "REGISTRATION_STARTED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const GET_STUDENT_LIST_STARTED = "GET_STUDENT_LIST_STARTED";
export const GET_STUDENT_LIST_FAILED = "GET_STUDENT_LIST_FAILED";
export const GET_STUDENT_LIST_SUCCESS = "GET_STUDENT_LIST_SUCCESS";

export const SET_SELECTED_MODULE = "SET_SELECTED_MODULE";
export const RESET_TOAST = "RESET_TOAST";